{
    "name": "Code Generator",
    "category": "Extra Tools",
    "summary": "Code Generator Module",
    "version": "12.0.0",
    "author": "Mathben (mathben@technolibre.ca)",
    "description": "An application to generate ERPLibre module.",
    "license": "AGPL-3",
    "application": True,
    "depends": [
        "base",
        "mail",
    ],
    "data": [
        "security/code_generator.xml",
        "security/ir.model.access.csv",
        "views/res_groups.xml",
        "views/ir_actions_act_url.xml",
        "views/ir_actions_act_window.xml",
        "views/code_generator_act_window.xml",
        "wizards/code_generator_add_controller_wizard.xml",
        "views/code_generator_ir_model_fields.xml",
        "wizards/code_generator_generate_views_wizard.xml",
        "views/code_generator_menu.xml",
        "views/ir_model_server_constrain.xml",
        "wizards/code_generator_add_model_wizard.xml",
        "views/code_generator_module.xml",
        "views/code_generator_module_dependency.xml",
        "views/code_generator_module_external_dependency.xml",
        "views/code_generator_module_template_dependency.xml",
        "views/code_generator_pyclass.xml",
        "views/code_generator_view.xml",
        "views/code_generator_view_item.xml",
        "views/code_generator_writer.xml",
        "views/code_generator_ir_model_dependency.xml",
        "views/code_generator_model_code.xml",
        "wizards/res_config_settings.xml",
        "views/ir_actions_todo.xml",
        "views/ir_model_fields.xml",
        "views/code_generator_model_code_import.xml",
        "views/ir_ui_menu.xml",
        "views/ir_model_constraint.xml",
        "views/ir_model.xml",
        "views/ir_model_access.xml",
        "views/ir_module_module.xml",
        "views/ir_actions_report.xml",
        "views/ir_actions_server.xml",
        "views/ir_ui_view.xml",
        "views/menu.xml",
    ],
    "demo": ["data/code_generator_demo.xml"],
    "installable": True,
    "post_init_hook": "post_init_hook",
}
